version: '3'

services:
  music-stream-service:
    build:
      context: ./music-stream-service
    ports:
      - "8000:5002"
    networks:
      - loadbalancing

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5003:5003"
    networks:
      - loadbalancing

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    networks:
      - loadbalancing

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - music-stream-service
      - payment-service
      - user-service

networks:
  loadbalancing:
