version: '3.8'

services:
  payment-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_db:5432/payments
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
